### ISSUE TITLE
Sensor characteristic curve

### ISSUE THREAD

**Issue by hari91github** [BoschSensortec/BMM050_driver#5]
1. Please include the sensor characteristic curve which shows the sensor response, 
2. Please provide some information about the flip-core technology.

**Comment by BoschSensortec** [comment]
Dear @hari91github ,

Please refer to the [datasheet](https://ae-bst.resource.bosch.com/media/_tech/media/datasheets/BST-BMM150-DS001-01.pdf) for information related to the BMM050/BMM150.

For more information not in the datasheet regarding the technology is subjected to a Non-Disclosure Agreement. Please fill out the [contact form](https://www.bosch-sensortec.com/bst/contact/contact_form/contact_form) and one of our representatives will contact you.
