### ISSUE TITLE
BMX055 Magnetometer going to an inconsistent state.

### ISSUE THREAD

**Issue by tejaskale** [BoschSensortec/BMM050_driver#7]
We are using the BMX055 sensor, and we are having problems with the magnetometer.
For unknown reasons, the magnetometer starts responding with 0's. It does not start responding with valid data until a physical power reset is done. Soft resets or even full power on resets done by trying to write a 0  to the last bit of the 0x4B(POWER_CNTL1) register. Other sensors(The accelerometer and the Gyro) work properly.

Further debugging shows us the following:
```
➜  ~ tail -f /tmp/ttyMain | grep -a STATE
1501697697.249052 STATE 19:0
1501697697.259596 STATE 27:0
1501697697.362532 STATE 36:255
1501697697.363190 STATE 19:255
1501697697.443742 STATE 36:255
1501697697.535554 STATE 19:255
1501697697.627330 STATE 36:255
1501697697.719195 STATE 19:255
1501697697.810993 STATE 36:255
```
I am trying to print the state of the 0x4B register.
`<timestamp> STATE <line number>:<0x4B state>

1. The first read reads it to be 0 (Meaning the device is in deep suspend)
2. I try to write a 1 to the power control bit(bit 0 of 0x4B) to try to wake it up.
3. The second read the register is 0. At this step if I add a delay of 10ms after the write, the read returns a 0   However if I wait 100ms, it returns a 0xFF(255) .
4. All subsequent writes to the register have no effect. The register state is always returned as 255.
5. All other registers for *ONLY* the magnetometer return 0's on trying to read them. The accelerometer and the gyroscope work fine.

According to the datasheet bits 3-6 of this register are reserved and fixed to 0. Which would mean that the register should never go to 0xFF!

I have observed  this issue on 2 independent sensors.

Any pointers on what could be going wrong are greatly appreciated.

Please advise on who to contact  if this is not the correct place to report this issue.

P.S : For our application, it is not possible to physically power cycle the  device since it is going be 600km from the surface of the Earth.

**Comment by BoschSensortec** [comment]
Hi @tejaskale ,

Since it is not a code related issue, the correct point of contact would be via our [Contact form](https://www.bosch-sensortec.com/bst/contact/contact_form/contact_form).

**Comment by tejaskale** [comment]
Thanks for the quick reply.
I have contacted you guys using the contact form.

**Comment by dragondgold** [comment]
@tejaskale did you got any reply about this? I'm facing the same problem!
